### ISSUE TITLE
Polish, Urdu and Arabic translations not working, crashing app

### ISSUE THREAD

**Issue by remaininlight** [yalla-coop/cost-of-living-support#141]
When Polish, Urdu or Arabic are selected as the language and the user navigates to 'Pay my bills' (https://staging.col-helper.co.uk/hyde/sections/2) the app crashes. The server log shows:

```
2022-12-05T20:00:18.450541+00:00 app[web.1]: TypeError: Cannot read property 'TranslatedText' of null
2022-12-05T20:00:18.450560+00:00 app[web.1]: at Response.<anonymous> (/app/server/node_modules/aws-translate-json/dist/index.js:56:30)
2022-12-05T20:00:18.450560+00:00 app[web.1]: at Request.<anonymous> (/app/server/node_modules/aws-sdk/lib/request.js:367:18)
2022-12-05T20:00:18.450561+00:00 app[web.1]: at Request.callListeners (/app/server/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2022-12-05T20:00:18.450561+00:00 app[web.1]: at Request.emit (/app/server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2022-12-05T20:00:18.450562+00:00 app[web.1]: at Request.emit (/app/server/node_modules/aws-sdk/lib/request.js:686:14)
2022-12-05T20:00:18.450562+00:00 app[web.1]: at Request.transition (/app/server/node_modules/aws-sdk/lib/request.js:22:10)
2022-12-05T20:00:18.450562+00:00 app[web.1]: at AcceptorStateMachine.runTo (/app/server/node_modules/aws-sdk/lib/state_machine.js:14:12)
2022-12-05T20:00:18.450562+00:00 app[web.1]: at /app/server/node_modules/aws-sdk/lib/state_machine.js:26:10
2022-12-05T20:00:18.450562+00:00 app[web.1]: at Request.<anonymous> (/app/server/node_modules/aws-sdk/lib/request.js:38:9)
2022-12-05T20:00:18.450563+00:00 app[web.1]: at Request.<anonymous> (/app/server/node_modules/aws-sdk/lib/request.js:688:12)
2022-12-05T20:00:18.451984+00:00 app[web.1]: 2022-12-05T20:00:18.450Z server an uncaught exception detected <ref *2> Error [TypeError]: Cannot read property 'TranslatedText' of null
2022-12-05T20:00:18.451984+00:00 app[web.1]: at Response.<anonymous> (/app/server/node_modules/aws-translate-json/dist/index.js:56:30)
2022-12-05T20:00:18.451984+00:00 app[web.1]: at Request.<anonymous> (/app/server/node_modules/aws-sdk/lib/request.js:367:18)
2022-12-05T20:00:18.451984+00:00 app[web.1]: at Request.callListeners (/app/server/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2022-12-05T20:00:18.451985+00:00 app[web.1]: at Request.emit (/app/server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2022-12-05T20:00:18.451985+00:00 app[web.1]: at Request.emit (/app/server/node_modules/aws-sdk/lib/request.js:686:14)
2022-12-05T20:00:18.451985+00:00 app[web.1]: at Request.transition (/app/server/node_modules/aws-sdk/lib/request.js:22:10)
2022-12-05T20:00:18.451986+00:00 app[web.1]: at AcceptorStateMachine.runTo (/app/server/node_modules/aws-sdk/lib/state_machine.js:14:12)
2022-12-05T20:00:18.451986+00:00 app[web.1]: at /app/server/node_modules/aws-sdk/lib/state_machine.js:26:10
2022-12-05T20:00:18.451986+00:00 app[web.1]: at Request.<anonymous> (/app/server/node_modules/aws-sdk/lib/request.js:38:9)
2022-12-05T20:00:18.451987+00:00 app[web.1]: at Request.<anonymous> (/app/server/node_modules/aws-sdk/lib/request.js:688:12) {
2022-12-05T20:00:18.451987+00:00 app[web.1]: code: 'TypeError',
2022-12-05T20:00:18.451988+00:00 app[web.1]: time: 2022-12-05T20:00:18.446Z,
2022-12-05T20:00:18.451988+00:00 app[web.1]: domainEmitter: <ref *1> Request {
2022-12-05T20:00:18.451989+00:00 app[web.1]: domain: Domain {
2022-12-05T20:00:18.451989+00:00 app[web.1]: _events: [Object: null prototype],
2022-12-05T20:00:18.451989+00:00 app[web.1]: _eventsCount: 2,
2022-12-05T20:00:18.451989+00:00 app[web.1]: _maxListeners: undefined,
2022-12-05T20:00:18.451989+00:00 app[web.1]: members: [Array],
2022-12-05T20:00:18.451990+00:00 app[web.1]: __SENTRY__: [Object],
2022-12-05T20:00:18.451990+00:00 app[web.1]: [Symbol(kCapture)]: false,
2022-12-05T20:00:18.451990+00:00 app[web.1]: [Symbol(kWeak)]: WeakReference {}
2022-12-05T20:00:18.451990+00:00 app[web.1]: },
2022-12-05T20:00:18.451990+00:00 app[web.1]: service: Service {
2022-12-05T20:00:18.451991+00:00 app[web.1]: config: [Config],
2022-12-05T20:00:18.451991+00:00 app[web.1]: isGlobalEndpoint: false,
2022-12-05T20:00:18.451991+00:00 app[web.1]: endpoint: [Endpoint],
2022-12-05T20:00:18.451991+00:00 app[web.1]: _events: [Object],
2022-12-05T20:00:18.451991+00:00 app[web.1]: MONITOR_EVENTS_BUBBLE: [Function: EVENTS_BUBBLE],
2022-12-05T20:00:18.451992+00:00 app[web.1]: CALL_EVENTS_BUBBLE: [Function: CALL_EVENTS_BUBBLE],
2022-12-05T20:00:18.451992+00:00 app[web.1]: _clientId: 6
2022-12-05T20:00:18.451992+00:00 app[web.1]: },
2022-12-05T20:00:18.451992+00:00 app[web.1]: operation: 'translateText',
2022-12-05T20:00:18.451992+00:00 app[web.1]: params: {
2022-12-05T20:00:18.451992+00:00 app[web.1]: SourceLanguageCode: 'en',
2022-12-05T20:00:18.451993+00:00 app[web.1]: TargetLanguageCode: 'ur',
2022-12-05T20:00:18.451993+00:00 app[web.1]: Text: 'Get help with debts'
2022-12-05T20:00:18.451993+00:00 app[web.1]: },
2022-12-05T20:00:18.451993+00:00 app[web.1]: httpRequest: HttpRequest {
2022-12-05T20:00:18.451993+00:00 app[web.1]: method: 'POST',
2022-12-05T20:00:18.451993+00:00 app[web.1]: path: '/',
2022-12-05T20:00:18.451994+00:00 app[web.1]: headers: [Object],
2022-12-05T20:00:18.451994+00:00 app[web.1]: body: '{"SourceLanguageCode":"en","TargetLanguageCode":"ur","Text":"Get help with debts"}',
2022-12-05T20:00:18.451994+00:00 app[web.1]: endpoint: [Object],
2022-12-05T20:00:18.451994+00:00 app[web.1]: region: 'eu-west-2',
2022-12-05T20:00:18.451994+00:00 app[web.1]: _userAgent: 'aws-sdk-nodejs/2.1267.0 linux/v14.21.1 callback',
2022-12-05T20:00:18.451994+00:00 app[web.1]: stream: [ClientRequest]
2022-12-05T20:00:18.451995+00:00 app[web.1]: },
2022-12-05T20:00:18.451995+00:00 app[web.1]: startTime: 2022-12-05T20:00:18.062Z,
2022-12-05T20:00:18.451995+00:00 app[web.1]: response: Response {
2022-12-05T20:00:18.451995+00:00 app[web.1]: request: [Circular *1],
2022-12-05T20:00:18.451995+00:00 app[web.1]: data: null,
2022-12-05T20:00:18.451995+00:00 app[web.1]: error: [Circular *2],
2022-12-05T20:00:18.451996+00:00 app[web.1]: retryCount: 3,
2022-12-05T20:00:18.451996+00:00 app[web.1]: redirectCount: 0,
2022-12-05T20:00:18.451996+00:00 app[web.1]: httpResponse: [HttpResponse],
2022-12-05T20:00:18.451996+00:00 app[web.1]: maxRetries: 3,
2022-12-05T20:00:18.451996+00:00 app[web.1]: maxRedirects: 10,
2022-12-05T20:00:18.451996+00:00 app[web.1]: requestId: '2d64ec5f-28f3-4978-a242-f71252478da7'
2022-12-05T20:00:18.451997+00:00 app[web.1]: },
2022-12-05T20:00:18.451997+00:00 app[web.1]: _asm: AcceptorStateMachine { currentState: 'complete', states: [Object] },
2022-12-05T20:00:18.451997+00:00 app[web.1]: _haltHandlersOnError: false,
2022-12-05T20:00:18.451997+00:00 app[web.1]: _events: {
2022-12-05T20:00:18.451997+00:00 app[web.1]: validate: [Array],
2022-12-05T20:00:18.451998+00:00 app[web.1]: afterBuild: [Array],
2022-12-05T20:00:18.451998+00:00 app[web.1]: restart: [Array],
2022-12-05T20:00:18.451998+00:00 app[web.1]: sign: [Array],
2022-12-05T20:00:18.451998+00:00 app[web.1]: validateResponse: [Array],
2022-12-05T20:00:18.451998+00:00 app[web.1]: error: [Array],
2022-12-05T20:00:18.451998+00:00 app[web.1]: send: [Array],
2022-12-05T20:00:18.451998+00:00 app[web.1]: httpHeaders: [Array],
2022-12-05T20:00:18.451999+00:00 app[web.1]: httpData: [Array],
2022-12-05T20:00:18.451999+00:00 app[web.1]: httpDone: [Array],
2022-12-05T20:00:18.451999+00:00 app[web.1]: retry: [Array],
2022-12-05T20:00:18.451999+00:00 app[web.1]: afterRetry: [Array],
2022-12-05T20:00:18.451999+00:00 app[web.1]: build: [Array],
2022-12-05T20:00:18.451999+00:00 app[web.1]: extractData: [Array],
2022-12-05T20:00:18.452000+00:00 app[web.1]: extractError: [Array],
2022-12-05T20:00:18.452000+00:00 app[web.1]: httpError: [Array],
2022-12-05T20:00:18.452000+00:00 app[web.1]: success: [Array],
2022-12-05T20:00:18.452000+00:00 app[web.1]: complete: [Array]
2022-12-05T20:00:18.452000+00:00 app[web.1]: },
2022-12-05T20:00:18.452001+00:00 app[web.1]: emit: [Function: emit],
2022-12-05T20:00:18.452001+00:00 app[web.1]: API_CALL_ATTEMPT: [Function: API_CALL_ATTEMPT],
2022-12-05T20:00:18.452001+00:00 app[web.1]: API_CALL_ATTEMPT_RETRY: [Function: API_CALL_ATTEMPT_RETRY],
2022-12-05T20:00:18.452001+00:00 app[web.1]: API_CALL: [Function: API_CALL],
2022-12-05T20:00:18.452001+00:00 app[web.1]: signedAt: 2022-12-05T20:00:18.383Z
2022-12-05T20:00:18.452002+00:00 app[web.1]: },
2022-12-05T20:00:18.452002+00:00 app[web.1]: domain: Domain {
2022-12-05T20:00:18.452002+00:00 app[web.1]: _events: [Object: null prototype] {
2022-12-05T20:00:18.452002+00:00 app[web.1]: removeListener: [Function: updateExceptionCapture],
2022-12-05T20:00:18.452002+00:00 app[web.1]: newListener: [Function: updateExceptionCapture]
2022-12-05T20:00:18.452002+00:00 app[web.1]: },
2022-12-05T20:00:18.452003+00:00 app[web.1]: _eventsCount: 2,
2022-12-05T20:00:18.452003+00:00 app[web.1]: _maxListeners: undefined,
2022-12-05T20:00:18.452003+00:00 app[web.1]: members: [ [IncomingMessage], [ServerResponse] ],
2022-12-05T20:00:18.452003+00:00 app[web.1]: __SENTRY__: { hub: [Hub] },
2022-12-05T20:00:18.452003+00:00 app[web.1]: [Symbol(kCapture)]: false,
2022-12-05T20:00:18.452003+00:00 app[web.1]: [Symbol(kWeak)]: WeakReference {}
2022-12-05T20:00:18.452003+00:00 app[web.1]: },
2022-12-05T20:00:18.452004+00:00 app[web.1]: domainThrown: false
2022-12-05T20:00:18.452004+00:00 app[web.1]: }
2022-12-05T20:00:18.464904+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2022-12-05T20:00:18.465132+00:00 app[web.1]: npm ERR! errno 255
2022-12-05T20:00:18.468687+00:00 app[web.1]: npm ERR! shannon-trust@0.0.1 start: `cross-env DEBUG=server node dist/index.js`
2022-12-05T20:00:18.468802+00:00 app[web.1]: npm ERR! Exit status 255
2022-12-05T20:00:18.468886+00:00 app[web.1]: npm ERR!
2022-12-05T20:00:18.468980+00:00 app[web.1]: npm ERR! Failed at the shannon-trust@0.0.1 start script.
2022-12-05T20:00:18.469063+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-12-05T20:00:18.477026+00:00 app[web.1]: 
2022-12-05T20:00:18.477124+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2022-12-05T20:00:18.477184+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2022-12-05T20_00_18_469Z-debug.log
2022-12-05T20:00:18.484659+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2022-12-05T20:00:18.484967+00:00 app[web.1]: npm ERR! errno 255
2022-12-05T20:00:18.488096+00:00 app[web.1]: npm ERR! hyde-cost-of-living-support@0.0.0 start: `cd server && npm start`
2022-12-05T20:00:18.488152+00:00 app[web.1]: npm ERR! Exit status 255
2022-12-05T20:00:18.488216+00:00 app[web.1]: npm ERR!
2022-12-05T20:00:18.488268+00:00 app[web.1]: npm ERR! Failed at the hyde-cost-of-living-support@0.0.0 start script.
2022-12-05T20:00:18.488319+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-12-05T20:00:18.492357+00:00 app[web.1]: 
2022-12-05T20:00:18.492451+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2022-12-05T20:00:18.492496+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2022-12-05T20_00_18_488Z-debug.log
```

**Team - do not edit**
@thejoefriel

**Comment by egasparini** [comment]
@dupreesi / @cemalokten can this be closed? it looks fine on staging now.

**Comment by dupreesi** [comment]
@egasparini the PR related to it wasn't merged yet so lets keep it open until that has happened? @RamyAlshurafa can we merge it?

**Comment by RamyAlshurafa** [comment]
done @dupreesi
